package com.company.enums;

public enum AdminStatus {
    CLICKED_ADD_PRODUCT,
    SELECT_CATEGORY_FOR_ADD_PRODUCT,
    ENTERED_PRODUCT_NAME,
    ENTERED_PRODUCT_PRICE,
    SEND_PRODUCT_IMAGE,
    COMMIT_OR_ROLLBACK_ADD_PRODUCT,
    BACK,
    NEW_PRODUCT_NAME_UPDATE,
    SELECT_PRODUCT_FOR_UPDATE_PRICE,
    SELECT_PRODUCT_FOR_UPDATE_NAME,
    ENTER_NEW_NAME_FOR_PRODUCT,
    NEW_PRODUCT_IMAGE_UPDATE,
    CHANGE_NAME,
    ENTER_NEW_PRICE_FOR_PRODUCT,
    CHANGE_NAME_BY_ID, CHANGE_PRICE, CHANGE_PRICE_BY_ID;
}
